nano_path:
    /pnfs/desy.de/cms/tier2/store/user/sobhatta/LongLivedStaus/NanoAOD

input:
    # stau100_lsp1_ctau100mm: /pnfs/desy.de/cms/tier2/store/user/sobhatta/LongLivedStaus/NanoAOD/SUS-RunIISummer20UL18GEN-stau100_lsp1_ctau100mm_v6
    # stau250_lsp1_ctau100mm: /pnfs/desy.de/cms/tier2/store/user/sobhatta/LongLivedStaus/NanoAOD/SUS-RunIISummer20UL18GEN-stau250_lsp1_ctau100mm_v6
    # stau400_lsp1_ctau100mm: /pnfs/desy.de/cms/tier2/store/user/sobhatta/LongLivedStaus/NanoAOD/SUS-RunIISummer20UL18GEN-stau400_lsp1_ctau100mm_v6

    # stau100_lsp1_ctau1000mm: /pnfs/desy.de/cms/tier2/store/user/sobhatta/LongLivedStaus/NanoAOD/SUS-RunIISummer20UL18GEN-stau100_lsp1_ctau1000mm_v4
    # stau250_lsp1_ctau1000mm: /pnfs/desy.de/cms/tier2/store/user/sobhatta/LongLivedStaus/NanoAOD/SUS-RunIISummer20UL18GEN-stau250_lsp1_ctau1000mm_v4
    # stau400_lsp1_ctau1000mm: /pnfs/desy.de/cms/tier2/store/user/sobhatta/LongLivedStaus/NanoAOD/SUS-RunIISummer20UL18GEN-stau400_lsp1_ctau1000mm_v4

    # "m(#tilde{#tau})=300 GeV c#tau_{0}=10000 mm": ${nano_path}/Stau_2018UL/SMS-TStauStau_MStau-300_ctau-10000mm_mLSP-1_TuneCP5_13TeV-madgraphMLM-pythia8/crab_SMS_TStauStau_MStau_300_ctau_10000mm_mLSP_1
    "m(#tilde{#tau})=300 GeV c#tau_{0}=1000 mm": ${nano_path}/Stau_2018UL/SMS-TStauStau_MStau-300_ctau-1000mm_mLSP-1_TuneCP5_13TeV-madgraphMLM-pythia8/crab_SMS_TStauStau_MStau_300_ctau_1000mm_mLSP_1
    # "m(#tilde{#tau})=300 GeV c#tau_{0}=100 mm": ${nano_path}/Stau_2018UL/SMS-TStauStau_MStau-300_ctau-100mm_mLSP-1_TuneCP5_13TeV-madgraphMLM-pythia8/crab_SMS_TStauStau_MStau_300_ctau_100mm_mLSP_1
    # "m(#tilde{#tau})=300 GeV c#tau_{0}=10 mm": ${nano_path}/Stau_2018UL/SMS-TStauStau_MStau-300_ctau-10mm_mLSP-1_TuneCP5_13TeV-madgraphMLM-pythia8/crab_SMS_TStauStau_MStau_300_ctau_10mm_mLSP_1
    # "m(#tilde{#tau})=300 GeV c#tau_{0}=1 mm": ${nano_path}/Stau_2018UL/SMS-TStauStau_MStau-300_ctau-1mm_mLSP-1_TuneCP5_13TeV-madgraphMLM-pythia8/crab_SMS_TStauStau_MStau_300_ctau_1mm_mLSP_1
    # "m(#tilde{#tau})=300 GeV c#tau_{0}=50 mm": ${nano_path}/Stau_2018UL/SMS-TStauStau_MStau-300_ctau-50mm_mLSP-1_TuneCP5_13TeV-madgraphMLM-pythia8/crab_SMS_TStauStau_MStau_300_ctau_50mm_mLSP_1
    # "m(#tilde{#tau})=300 GeV c#tau_{0}=5 mm": ${nano_path}/Stau_2018UL/SMS-TStauStau_MStau-300_ctau-5mm_mLSP-1_TuneCP5_13TeV-madgraphMLM-pythia8/crab_SMS_TStauStau_MStau_300_ctau_5mm_mLSP_1
    # # "m(#tilde{#tau})=300 GeV c#tau_{0}=0.5 mm": ${nano_path}/Stau_2018UL/SMS-TStauStau_MStau-300_ctau-0p5mm_mLSP-1_TuneCP5_13TeV-madgraphMLM-pythia8/crab_SMS_TStauStau_MStau_300_ctau_0p5mm_mLSP_1
    # "m(#tilde{#tau})=300 GeV c#tau_{0}=0.1 mm": ${nano_path}/Stau_2018UL/SMS-TStauStau_MStau-300_ctau-0p1mm_mLSP-1_TuneCP5_13TeV-madgraphMLM-pythia8/crab_SMS_TStauStau_MStau_300_ctau_0p1mm_mLSP_1
    # # "m(#tilde{#tau})=300 GeV c#tau_{0}=0.05 mm": ${nano_path}/Stau_2018UL/SMS-TStauStau_MStau-300_ctau-0p05mm_mLSP-1_TuneCP5_13TeV-madgraphMLM-pythia8/crab_SMS_TStauStau_MStau_300_ctau_0p05mm_mLSP_1
    # "m(#tilde{#tau})=300 GeV c#tau_{0}=0.01 mm": ${nano_path}/Stau_2018UL/SMS-TStauStau_MStau-300_ctau-0p01mm_mLSP-1_TuneCP5_13TeV-madgraphMLM-pythia8/crab_SMS_TStauStau_MStau_300_ctau_0p01mm_mLSP_1
    # "DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8": ${nano_path}/DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/crab_DYJetsToLL_M-50

input_disID: null
# input_disID:
#     test1: /nfs/dust/cms/user/mykytaua/softLLSTAU/LLStaus_Run2/soft/CMSSW_12_4_0/src/output_id/

n_files: -1 #per dataset

codes: 5

mode:

    # in jet_dR_matching mode the 2D plots with dR between:
    # dR_STau_Tau vs. dR_STau_Jet
    # dR_STau_Jet vs. dR_STau_lostTrack
    # dR_STau_Jet vs. dR_STau_pfCand
    # dR_Tau_STau vs. dR_Tau_Jet
    - jet_dR_matching

    # in efficiency_study efficiency plots are produced:
    # seeding efficiency for pt and Lxy
    - efficiency_study

collections:
    GenJets:
        name: GenJet
        cut: "({name}.pt > 20) & (abs({name}.eta) < 2.3)"
    Jets:
        name: Jet
        #name: CaloJet
        cut: "({name}.pt > 20) & (abs({name}.eta) < 2.3)"
    Tau:
        name: Tau
        cut: "({name}.pt > 20) & (abs({name}.eta) < 2.3) & ({name}.idDeepTau2018v2p5VSe	>= 1) & ({name}.idDeepTau2018v2p5VSmu >= 1) & ({name}.idDeepTau2018v2p5VSjet >= 1)"
    GenVisTaus:
        name: GenVisTau
        cut: "({name}.pt > 20) & (abs({name}.eta) < 2.3) & (abs({name}.vertexZ) < 10) & (abs({name}.vertexRho) < 50)"
        # cut: "({name}.pt > 20) & (abs({name}.eta) < 2.3) & (abs({name}.vertexZ) < 50)"
        # cut: "({name}.pt > 20) & (abs({name}.eta) < 2.3)"
    STau:
        vertexZ: 10 #cm cut 

bin_setups:
    dR_bins  : [100, 0.0, 0.8]  # n_bins, dR_min, dR_max
    Lxy_bins : [0.0, 0.001, 0.01, 0.05, 0.1, 1.0, 5.0, 10.0, 15.0, 20.0, 25.0, 30.0, 50.0, 70.0, 80.0, 100.0, 200.0] # bin edges in cm
    Lxy_slice : [ [0, 1.0], [1.0, 10.0], [10.0, 30.0], [30.0, 50.0], [50.0, 100.0], [100.0, 200.0]] # also in cm (bin edges)


eff_setups:
    gen_jet_pt  : [15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 90, 100, 150, 200, 250, 300, 1000] # n_bins, pt_min, pt_max
    # Lxy_bins : [0.0, 0.001, 0.01, 0.1, 1.0, 5.0, 10.0, 15.0, 20.0, 25.0, 30.0, 50.0, 70.0, 80.0, 100.0] # bin edges in cm
    # Lxy_bins : [0.0, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 5.0, 10.0, 15.0, 20.0, 50.0, 100.0] 
    # Lxy_slice : [ [0, 0.1], [0.1, 1.0], [1.0, 3.0], [3.0, 5.0], [1.0, 10.0], [10.0, 30.0], [30.0, 50.0], [50.0, 100.0]] # also in cm (bin edjes)
    # Lxy_bins : [0.0, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 5.0, 10.0, 15.0, 20.0, 50.0, 100.0] 
    # Lxy_slice : [ [0, 0.1], [0.1, 1.0], [1.0, 3.0], [3.0, 5.0], [1.0, 10.0], [10.0, 30.0], [30.0, 50.0], [50.0, 100.0]] # also in cm (bin edjes)
    Lxy_bins : [0.0, 0.001, 0.01,  0.1, 0.4, 1.0, 4.0, 10.0, 14.0, 20.0, 50.0, 70.0, 100.0] 
    Lxy_slice : [ [0, 100.0] ] # also in cm (bin edjes)
    energy_ratio: [100, 0.9, 2.0]
    energy_ratio_children: [100, 0.9, 1.1]
    pt_ratio : [100, 0.0, 2.0, 100, 0, 1000]
    pt_resolution : [100, -1, 5, 100, 0, 1000]

output: /nfs/dust/cms/user/mykytaua/softLLSTAU/LLStaus_Run2/plots_DP_post-pog/efficiency_coordfix_vz10cm_vrpo50cm/
# output: /nfs/dust/cms/user/mykytaua/softLLSTAU/LLStaus_Run2/plots_DP_post-pog/efficiency_coordfix_vz50cm/